### PR TITLE
fix: typings known issues

### LINKED ISSUE #676: please fix typings known issues
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `json-schema-faker@0.5.0-rcv.39` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/json-schema-faker/index.d.ts b/node_modules/json-schema-faker/index.d.ts
index 605b1a7..4fd18fe 100644
--- a/node_modules/json-schema-faker/index.d.ts
+++ b/node_modules/json-schema-faker/index.d.ts
@@ -1,7 +1,7 @@
 import type { JsonValue, JsonObject } from 'type-fest';
 import type { JSONSchema4, JSONSchema6, JSONSchema7 } from 'json-schema';
 
-type Schema = JSONSchema4 | JSONSchema6 | JSONSchema7;
+export type Schema = JSONSchema4 | JSONSchema6 | JSONSchema7;
 
 export interface JSONSchemaFakerOptions {
   defaultInvalidTypeProduct?: boolean;
@@ -37,9 +37,9 @@ export interface JSONSchemaFakerDefine {
   (value: JsonValue, schema: JsonObject, property: string, rootSchema: Schema, propertyPath: string[]): JsonValue;
 }
 
-interface JSONSchemaFakerFormat {
-  (opts: { [k: string]: (value: Schema) => string }): void;
-  (name: string, callback: (value: Schema) => string): void;
+export interface JSONSchemaFakerFormat {
+  (opts: { [k: string]: (value: Schema) => unknown }): void;
+  (name: string, callback: (value: Schema) => unknown): void;
 }
 
 declare function JSONSchemaFakerOption(opts: JSONSchemaFakerOptions): void;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by JounQin**
close #676

### CODE REVIEW

**Comment by pateketrueke** [comment]
Let me understand it first, what caused your issue?

I thought exporting those types/interfaces were not needed, unless you import them, what makes totally sense!

**Comment by JounQin** [comment]
I'm using this library to generate response for mock based on route on Server.

**Comment by pateketrueke** [comment]
Sure, just I still don't get how the patch solves the issue, you're using typescript?

**Comment by JounQin** [comment]
> Sure, just I still don't get how the patch solves the issue, you're using typescript?

Yes, strictly.

**Comment by pateketrueke** [comment]
Oh, got it, I did not realized that before. Thank you!

**Pull request merged**
