### PR TITLE
feat: migrate to faker v7

### LINKED ISSUE #691: Migration to @faker-js/faker 6.0.0
Hello :wave: 
I'm one of the maintainer of https://github.com/faker-js/faker and we expect to release a beta or RC in the next few days/week.
I would like to create a PR that migrates to the new version, so we can see if anything needs to be done before officially releasing the `6.0.0`.

### PR DESCRIPTION
**Pull request by Shinigami92**
closes #691

### CODE REVIEW

**Comment by Shinigami92** [comment]
Okay, somehow the cjs require does not work correctly :thinking: 

In [`tests/schema/core/extend/faker-extend.js`](https://github.com/json-schema-faker/json-schema-faker/blob/e3f5fc671d05f740c16efb5db43a30a66d6f7f3b/tests/schema/core/extend/faker-extend.js#L3) we would currently need to use `const faker = require('@faker-js/faker/dist/cjs/locale/de');`
Maybe this is related to https://github.com/faker-js/faker/issues/462 :thinking: 
In TypeScript or using `esm` everything works. But not the `cjs` version

**Comment by Shinigami92** [comment]
https://github.com/faker-js/faker/pull/520

**Comment by Shinigami92** [comment]
@pateketrueke Please trigger the GH actions, but do not merge yet.
I will update this PR when `6.0.0` is officially out.

**Comment by Shinigami92** [comment]
@pateketrueke Please retrigger pipeline, I updated to `beta.0`

**Comment by ST-DDT** [comment]
@Shinigami92 This needs to be updated to faker v6.1.1

**Review by ST-DDT — DISMISSED** [review]

**Pull request closed without merging**
