### PR TITLE
integerType returns uniformly distributed integer

### LINKED ISSUE #431: Random integer is not uniform
If I use `{"type":"integer","minimum":0,"maximum":1}`
I always get 1.

Tested on 0.5.0-rc15.

If we agree this is a bug, I could provide a PR

### PR DESCRIPTION
**Pull request by MrChoclate**
Fix #431

### CODE REVIEW

**Comment by pateketrueke** [comment]
Hi, thank you for your contribution.

Sadly I have to say this PR is not even passing the tests.

I don't think is a trivial change, ensure the tests passes locally to ensure your changes are not breaking anything else.

Again, thank you!

**Comment by MrChoclate** [comment]
Better?

**Comment by pateketrueke** [comment]
Awesome work! 🎉 

Now, to be sure can you add at least one `.json` file to test this out?

Just add something like this `spec/schema/core/issues/issue-431.json`:

```json
[
  {
    "description": "uniform distribution for integers",
    "tests": [
      {
        "description": "should pass ...",
        "schema": {
          "type": "integer",
          "minimum": 0,
          "maximum": 1
        },
        "equal": ?,
        "valid": true
      }
    ]
  }
]
```

**Comment by pateketrueke** [comment]
Merged on `develop`

**Pull request closed without merging**
