### PR TITLE
Bugfix: invalid time value toISOString

### LINKED ISSUE #539: RangeError: Invalid time value at Date.ISOString
Total beginner here.

I am getting an "Error: RangeError: Invalid time value" when having a schema such as below. This used to work against a much older version. 

image

I validated the schema if its correct. 
image

### PR DESCRIPTION
**Pull request by lhimstedt**
Introduce a new clampDateTime method to force all number parts in the string to be two-digit. Also, this method keeps the time part of the string.
Added the two-digit enforcement to the clampDate method too.

Fix #539 and fixes the base problem in #705

### CODE REVIEW

**Comment by lhimstedt** [comment]
@pateketrueke Here we go agagin.

**Review by pateketrueke — APPROVED** [review]
Awesome, thank you!

**Comment by pateketrueke** [comment]
@lhimstedt the latest version (0.5.0-rcv.42) has it, see: https://npmfs.com/package/json-schema-faker/0.5.0-rcv.42/dist/main.cjs.js

**Comment by lhimstedt** [comment]
@pateketrueke Okay, then my search function had an index problem or I missed something.

**Comment by lhimstedt** [comment]
@pateketrueke When do you think the new version with the bugfix will be released on NPM?

**Comment by pateketrueke** [comment]
@lhimstedt I already released `0.5.0-rcv.43`

**Comment by lhimstedt** [comment]
@pateketrueke Perfect, thanks. It makes handling a lot easier than a local package.

**Comment by lhimstedt** [comment]
@pateketrueke I think my changes are missing in 0.5.0-rcv.43.

Looking for clampDateTime in
https://npmfs.com/package/json-schema-faker/0.5.0-rcv.43/dist/main.cjs.js

**Pull request merged**
