### PR TITLE
fixed issue #238 and added unit tests for it

### PR DESCRIPTION
**Pull request by 0xBADBAC0N**

### CODE REVIEW

**Comment by pateketrueke** [comment]
Pleas read our [CONTRIBUTING](https://github.com/json-schema-faker/json-schema-faker/blob/master/.github/CONTRIBUTING.md) guidelines, all PR must be against the `develop` branch.

BTW; I think that issue is already solved on `develop`, but i'm not sure, the test you added worth it.

Can you test against `develop` please?

**Comment by 0xBADBAC0N** [comment]
Hi,
yes i did read the notes now, i am sorry.
I noticed it to late that it is partly fixed in the dev branch.
There is still the bug that empty arrays gets removed (the unit test cover this).

**Comment by pateketrueke** [comment]
Fine, could you try the same fix on `ts/core/utils.ts` ?

**Comment by 0xBADBAC0N** [comment]
I tried, but then an other unit test from you breaks.
I will look in this later this week when i have some more time.
(i guess one of the old unit tests breaks because if i allow null objects for json, this is not covered by some tests which will break then)

**Pull request closed without merging**
