### PR TITLE
Allow for nested arrays.

### LINKED ISSUE #282: Cannot create nested arrays.
Description
==
http://json-schema-faker.js.org/#gist/b02a603d2b83004c7c67510b05ce216a/0.5.0-rc5 shows that when one of the items in an array type property is itself an array, the items are put into the parent array instead of the sub-array.

Expected:
==

```json
{
  "nestedArrays": [
    [
      -32420639,
      53102032,
    ],
    "dol"
  ]
}
```

Actual:
==

```json
{
  "nestedArrays": [
    -32420639,
    53102032,
    "dol"
  ]
}
```

### PR DESCRIPTION
**Pull request by Riobe**
This pull request removes a check that will remove empty arrays and switches from a `.apply` to a `.call` which will stop turning nested arrays into parameters, requiring doubly nested arrays to work around.

Fixes #282 and #283

### CODE REVIEW

**Comment by Riobe** [comment]
There are failing tests, but I'm not sure what to do about those. They seem to be indicating that you **want** empty nested arrays to be nuked out, but that's specifically what I would like to stop from happening. If I create a schema that is valid and would create an empty nested array, then I don't want it to be removed for some reason. I'm not going to try to "fix" the tests unless I get feedback that this is a desired change.

**Comment by Riobe** [comment]
I also just noticed I need to change this to be for the develop branch. I'll make that change too once I find out if this change is actually desired or not.

**Comment by pateketrueke** [comment]
> If I create a schema that is valid and would create an empty nested array, then I don't want it to be removed for some reason.

I'm interested on see a schema that would produce empty nested arrays, and see how you deal with the results.

Anyway, what we can do is allowing both behaviours through setting an option.

**Comment by Riobe** [comment]
@pateketrueke Thanks for responding! I can make it based on an option, though what would be the default value? I don't honestly understand the logic of removing values created by a valid JSON schema just because they happen to be empty arrays. Why are those treated special? Though, I could see wanting to make leaving them in the default to not break anyone that has relied on that behavior previously...

The fix for #282 is in here, and is just changing the `.apply` call in types/array.ts to a `.call`. [`Function.prototype.apply`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) will take an array of things and send each one in as a parameter, instead of the array as a parameter, effectively un-nesting the array by a level. Doubly nested arrays will come through as singly nested due to this.
 
Lastly, can you help me a bit with how to build? I switched to the `develop` branch to try to put my change on there, but it can't `npm install` due to relying on `"tamira": "^2.0.1"` (unlike `master` which relies on `"tamira": "^3.2.1"`) and everything from `npm view tamira@^2.0.1 dependencies` show those versions of tamira relying on non-existent versions of wargs. Am I ok to up the tamira version on `develop`? Or can I try to fix `master`? However you'd like.

**Comment by pateketrueke** [comment]
Oh, the `develop` branch was outdated. Now is up-to-date with master.

All the build scripts now should be working fine, so please stick on the `develop` branch.

BTW; if the change was only `.call` I think it would be fine your current PR.

Just check how the `utils.clean()` function is working and fix it, probably adding some unit tests for it, because it can receive options (?).

Me previous concern on pruning empty values was for getting some recursive objects:

```js
{
  result: [
    [{}, {}, {}],
    [
      [{}, {}],
    ],
  ],
}
```

Where sometimes the `{}` is result of a self-reference, or something deep like that.

Once a maximum depth is reach the `traverse/reduce` loop will remove any reference left, and then return the object in-place.

So, the first step may be removing empty objects, or not? I'm not sure on this topic...

But if we remove empty object we obtain this:

```js
{
  result: [
    [undefined, undefined, undefined],
    [
      [undefined, undefined],
    ],
  ],
}
```

And then, just filter out undefined values resulting:


```js
{
  result: [
    [],
    [
      [],
    ],
  ],
}
```

Now we can remove all empty arrays and get this:

```js
{
  result: [],
}
```

If you ask, **I'm not sure what I'm doing** about this topic.

Please let me know what you think about. :)

Thanks for your feedback!

**Comment by pateketrueke** [comment]
It was quick to test your changes! 🍻 

After some thinking I realized that keeping empty arrays is a good thing, but we need to explore edge cases where really you don't expect it.

I'm closing this but please open an issue if you think we need to discuss more about this topic.

Again, so much thanks for your patience and valuable input/code!

**Pull request merged**
