### PR TITLE
Fix again min and maxItem generation

### PR DESCRIPTION
**Pull request by XVincentX**
Not too sure what was the original intention, but the code is still not working correctly.

### CODE REVIEW

**Comment by XVincentX** [comment]
@pateketrueke

**Comment by pateketrueke** [comment]
Interesting, I ran the tests on every release and they look fine. Can you try `npm test` to make sure this is ok?

**Comment by XVincentX** [comment]
Tests are all passing, so they were before the previous PR.

I think that either the tests are incorrect or they were never written to test the bounds

**Comment by pateketrueke** [comment]
I see, then rc31 is a regression, right? If this change would make it work as on rc30 we need to refine what should be the meaning behind the motivation of your changes.

Why the previous release did not fulfil your requirements? 🤔

**Comment by XVincentX** [comment]
Well basically what I'm trying to is to make sure that if the schema has already `maxItems` and `minItems` — the option values should not be used.

I can see there's some sort of logic to make sure the boundaries are "correct", but I haven't been able to figure out what's the real intent.

**Comment by pateketrueke** [comment]
Could you bring more use cases or samples to compare?

**Comment by XVincentX** [comment]
Yes, let's see if I can craft a more precise example.

**Comment by XVincentX** [comment]
@pateketrueke Added another test.

**Comment by pateketrueke** [comment]
TravisCI is getting too slow lately... 😞 

I'm going to include your changes by hand, then I'll enable GitHub Actions in order to quickly get CI results!

So much thanks for your time and feedback, see you there! :beers:

**Comment by XVincentX** [comment]
Great, thank you very much. Are you also going to release so I can include it in Prism and release it? Thanks!

**Comment by pateketrueke** [comment]
Yeah, please make sure your changes and the tests make sense for you, please let me know!

**Comment by pateketrueke** [comment]
https://github.com/json-schema-faker/json-schema-faker/commit/6e30bc8f730bc4b6803c0fef2f5300cbdb77df23

**Comment by XVincentX** [comment]
Works correctly! Let's release it!

**Pull request closed without merging**
