### PR TITLE
Allow custom format for additionalProperties property names

### PR DESCRIPTION
**Pull request by jsayol**
When generating data for `additionalProperties`, the property names are random strings (`words(1) + randexp('[a-f\\d]{4,7}')`). The proposed `additionalProperties` allows to use any defined custom format to generate the property names.

For example, having this custom format (as shown in the docs):

```javascript
jsf.format('semver', function(gen, schema) {
  return gen.randexp('^\\d\\.\\d\\.\\d{1,2}$');
});
```

And the following JSON schema:

```json
{
  "type": "object",
  "properties": {
    "versions": {
      "type": "object",
      "minProperties": 4,
      "maxProperties": 8,
      "additionalPropertiesFormat": "semver",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "author": {
          	"faker": "name.findName"
          },
          "changes": {
          	"faker": { "random.number": [99] }
          }
        },
        "required": [
          "author",
          "changes"
        ]
      }
    }
  },
  "required": [
    "versions"
  ]
}
```

A posible generated output is as follows:

```json
{
  "versions": {
    "1.8.1": {
      "author": "Lilian Schamberger",
      "changes": 85
    },
    "0.5.71": {
      "author": "Arnoldo Cormier",
      "changes": 41
    },
    "4.9.08": {
      "author": "Arianna Windler",
      "changes": 30
    },
    "5.1.12": {
      "author": "Gabriel Schuster",
      "changes": 69
    },
    "1.2.93": {
      "author": "Sheldon Yundt",
      "changes": 18
    },
    "0.1.51": {
      "author": "Meaghan Dach",
      "changes": 47
    }
  }
}
```

### CODE REVIEW

**Comment by jsayol** [comment]
Oh, uh, something went wrong. That's a lot of commits and they're not mine :/

**Comment by jsayol** [comment]
It seems the `develop` branch is quite behind `master`. Should i cancel the PR and create it again against `master`?

**Comment by pateketrueke** [comment]
I've synced branches, please pull changes and merge locally before we can proceed.

Also please check [our contribution guide](https://github.com/json-schema-faker/json-schema-faker/blob/master/.github/CONTRIBUTING.md) and update your PR according.

**Comment by jsayol** [comment]
> I've synced branches, please pull changes and merge locally before we can proceed.

:+1: 

> Also please check our contribution guide and update your PR according.

Sorry, I thought I did but I just skimmed through the guide and clearly missed some steps.

**Pull request closed without merging**
