### PR TITLE
dev sync: several fixes and updates

### PR DESCRIPTION
**Pull request by pateketrueke**
## Work in progress

This PR would resolve several mistakes from bundles, from now on the published packages should be stable for ESM and for usage on Deno.

It also includes other small contributions as well minor corrections, we want to include more fixes and small features before the next release!

### CODE REVIEW

**Comment by rfoel** [comment]
@pateketrueke any plans on creating this release?

**Comment by pateketrueke** [comment]
Hi @rfoel and so much thanks for your contributions, I have not been able to sit down and close some more issues we have. I would not mind if we release this as is, and later work some more issues. What do you think? It is really urgent? If yes, then I'll put hands on this weekend. Otherwise probably will be before the end of the month. No rush, again, thank you!

**Comment by rfoel** [comment]
@pateketrueke I've noticed you've been putting out a lot of RCs. Honestly, I don't really see the point in holding back another RC. But it's your call, and if you think it's worth it for the users, then ok. Maybe you could even do a prerelease, although I don't know if that makes much sense for an RC. Anyway, I'm cool with whatever you decide, and I'm here to help if you need it.

**Comment by jonesphi** [comment]
@pateketrueke Do you have a target date for this release?

**Pull request merged**
