### PR TITLE
feat: YAML rendering with meta comments

### LINKED ISSUE #609: YAML output
Adding a YAML/... output option would be nice. I know that one could convert the resulting JSON to YAML or something else, but my use case actually requires directly outputting YAML. I would like to add `"description"` tags to the output in the form of comments. That way I can auto-generate parts of the documentation. Is this something you would merge? I have written something similar in go but very specific for one project. My hope is that we can replace it with JSON Schema Faker.

### PR DESCRIPTION
**Pull request by zepatrik**
Closes #609

I will add more tests and fix stuff tomorrow, this is a first draft. Feel free to criticize my approach and suggest basic misconceptions.

There is now a context that is populated together with the value during schema traversal. Currently it holds some meta information, but there can be added more in the future. I propose new top level APIs to expose the context and also to render YAML output.

### CODE REVIEW

**Review by pateketrueke — COMMENTED** [review]
Actually looks pretty good to me, did you verify if the resolve method is still working too?

**Comment by zepatrik** [comment]
Fixing tests now to make sure that the current API still works the same way.

**Comment by zepatrik** [comment]
So still some last failing cases, most of the stuff works. Will continue over the next days.

**Comment by zepatrik** [comment]
Ah should I roll back to package lock file v1?

**Review by pateketrueke — APPROVED** [review]
Awesome, thank you!

**Comment by zepatrik** [comment]
Thank you for this project and continuous work :tada:

**Pull request merged**
