### PR TITLE
Prune empty props (arrays/objects)

### PR DESCRIPTION
**Pull request by pateketrueke**
With this PR `jsf` would remove empty properties from generated objects, only empty arrays and objects are discarded.

Also a spec was added to cover this issue on `spec/core/issues/empty-props.json`, see #106 for more details.

> FYI: I've added `spec/core/issues/anonymous.json` in order to verify #113 which is actually about non well formed schemas, I think there is no much to do with it...

### CODE REVIEW

**Comment by ducin** [comment]
damn, I missed that one... could you please rebase it (or merge) with current `develop` branch?

**Comment by ducin** [comment]
would be nice if you could update this one with latest version (no matter master od develop) - just the typescript one.

**Comment by pateketrueke** [comment]
Updated! :beer:

**Comment by ducin** [comment]
need to clean it... some files are still outdated. New commits arriving :beers:

**Comment by ducin** [comment]
@pateketrueke I did some significant changes there since the branch was neither merged nor rebased. I removed all changes that seemed to be accidental (and probably were results of TypeScript changes done in the meantime). I also had to reintroduce getSubAttribute function which was removed in your branch. Don't know if it was intentional, but many integration tests were failing with this function missing.

I tried a rebase, but I gave up after 20 minutes :P and eventually did a merge.

Now all tests are passing. But please take a look at the code to see if the merge is correct. And if not... :beers:

**Comment by ducin** [comment]
PS does it solve any issues opened?

**Comment by pateketrueke** [comment]
> PS does it solve any issues opened?

See: #106

**Pull request merged**
