### PR TITLE
Replacing "alwaysFakeOptionals" option for "alwaysFakeProbability".

### PR DESCRIPTION
**Pull request by manuelmhtr**
## Problem
Currently, the library generates only up to 5 optional properties (usually only 1 - 3). This number does not consider schema's size (ie. 3 optional properties might be a lot for small schemas, but almost nothing for big ones).

`alwaysFakeOptionals` is a good option to generate those properties, however it doesn't permit them to be empty.

## Solution
Replace `alwaysFakeOptionals` option for `fakeOptionalsProbability` that accepts a number between 0 and 1 and indicates the fraction of optional properties to be generated.

When `fakeOptionalsProbability = 1.0` it behaves the same than `alwaysFakeOptionals = true`.

Default value for `fakeOptionalsProbability` is `0.0` which means no optional properties will be generated (as actual behaviour). 

`0.5` will generate half of optional properties and so on...

### CODE REVIEW

**Comment by pateketrueke** [comment]
The only thing I don't want to change much are the options, we can just enhance the `alwaysFakeOptionals` option rather than eliminating it.

Let's say `alwaysFakeOptionals` can be a boolean, or a number between `1.0` and `0.0`.

What do you think?

**Comment by pateketrueke** [comment]
> alwaysFakeOptionals would have precedence. That is, if alwaysFakeOptionals = true then optionalsProbability will be 1.0 and ignore input.

Totally agree, `optionalsProbability` would be fine. 👍

**Comment by manuelmhtr** [comment]
Done 😎

**Comment by pateketrueke** [comment]
Cool, just I think we're missing some tests to ensure we got 0-100% of probablitites depending on the given value.

We don't have (yet) any assert implemented to test that results, I'll merge your PR and then think about adding a few more specialized tests for this feature.

**Pull request merged**
