### PR TITLE
Replace empty value by random value

### PR DESCRIPTION
**Pull request by oktapodia**
Add the `replaceEmptyByRandomValue` to avoid empty value

### CODE REVIEW

**Comment by oktapodia** [comment]
Some not related tests are failing (should not be related to that PR)

**Comment by pateketrueke** [comment]
I like this, but the name `replaceEmptyByRandomValue` is not quite clear because we're not replacing anything, also _empty_ means lots of things, what about empty arrays?

I would like more to use `defaultToRandom` or `randomDefault`, simpler, and makes explicit what it does.

Can you update your PR with a better name for such option? Thank you! 🍻

**Comment by oktapodia** [comment]
Thank you for your comment, I'm happy to replace the name of the option but I'm not sure `defaultToRandom` or `randomDefault` are right neither.

My feature is to replace the `''` default value by something random (just to avoid `''` in DB and help for testing purpose), it won't replace the nonEmpty string.

What is your thought?

**Comment by pateketrueke** [comment]
So, you're saying it only affects when `default` is an empty string and nothing else? 🤔 

Then `replaceEmptyDefaultByRandomValue` would read correct, verbose but correct.

**Pull request merged**
