### PR TITLE
add support for `contains` in arrays

### LINKED ISSUE #585: Json-schema-faker doesn't work as expected with "contains" keyword
Input Schema 
`{
  "type": "object",
  "required": [
    "Header"
  ],
  "properties": {
    "Header": {
      "type": "object",
      "required": [
        "Address"
      ],
      "properties": {
        "Address": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "AddressTypeCode"
            ],
            "properties": {
              "AddressTypeCode": {
                "type": "string"
              }
            }
          },
          "minItems": 2,
          "allOf": [
            {
              "contains": {
                "required": [
                  "AddressTypeCode"
                ],
                "type": "object",
                "properties": {
                  "AddressTypeCode": {
                    "type": "string",
                    "enum": [
                      "ST"
                    ]
                  }
                }
              }
            },
            {
              "contains": {
                "required": [
                  "AddressTypeCode"
                ],
                "type": "object",
                "properties": {
                  "AddressTypeCode": {
                    "type": "string",
                    "enum": [
                      "SF"
                    ]
                  }
                }
              }
            }
          ]
        }
      },
      "description": "Encloses all document header elements."
    }
  }
}`

Result from : https://json-schema-faker.js.org/
`{
  "Header": {
    "Address": [
      {
        "AddressTypeCode": "est adipisicing magna cillum voluptate"
      },
      {
        "AddressTypeCode": "cillum in sint dolor"
      }
    ]
  }
}`

Expected Result : 
`{
  "Header": {
    "Address": [
      {
        "AddressTypeCode": "ST"
      },
      {
        "AddressTypeCode": "SF"
      }
    ]
  }
}`

### PR DESCRIPTION
**Pull request by Hades32**
Simply replaces one index of the generated array with an item that matches the `contains` schema.

Resolves #585

### CODE REVIEW

**Comment by pateketrueke** [comment]
Could you add, at least, a schema that covers the feature right under `tests/schema/core/issues` please? Thank you!

**Comment by Hades32** [comment]
done 👍

**Comment by Hades32** [comment]
@pateketrueke anything I should do?

**Comment by pateketrueke** [comment]
Sorry @Hades32 I forgot to follow this one, one it passes CI I'll merge it, idk how to disable/remove the other checks...

**Comment by Hades32** [comment]
Great @pateketrueke !

I think those other checks from GitHub integrations. You can find them in the settings of the repository. Maybe the API-key of those has expired

**Pull request merged**
