### PR TITLE
Add schema selection and array size callbacks

### PR DESCRIPTION
**Pull request by alisters**
These are the only changes inside json schema faker, but the changes don't make too much sense without me supplying the callback functions. I'll add those tonight

These changes are for discussion only and not production ready - don't merge yet please !

### CODE REVIEW

**Comment by pateketrueke** [comment]
Hi @alisters, thanks for your contribution!

You edited `.js` files but they're generated, please apply these changes into the `.ts` sources to see the actual result.

**Comment by alisters** [comment]
ok - new to typescript, but I'll give it a go.

**Comment by alisters** [comment]
Adding some example code that i've tested this with. I have a more realistic example too - i'll attach that tomorrow (it's quite difficult to get code off my work computer and I can't interact with github at work !)

I'm guessing writing a test is the better way to incorporate these kinds of example code, so I'll give that a go too !

`
(async () => {

    var jsf = require('json-schema-faker');
    var ptr = require('json-ptr');
    var merge = require('deepmerge');
    var traverse = require('traverse');

    jsf.option({
        schemaChoiceCallback: schemaChoiceCallbackFunction,
        arraySizeCallback: arraySizeCallbackFunction
    })

    var schema =
        {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "Test Hierarchy",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "A": {
                    "type": "string"
                },
                "B": {
                    "type": "array",
                    "items": {
                        "oneOf": [
                            {
                                "$ref": "#/definitions/C"
                            },
                            {
                                "$ref": "#/definitions/D"
                            }
                        ]
                    }
                }
            },
            "required": [
                "A",
                "B"
            ],

            "definitions": {
                "C": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "TypeDiscriminator": {
                            "type": "string",
                            "enum": [
                                "C"
                            ]
                        },

                        "SomeValue": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "TypeDiscriminator",
                        "SomeValue"
                    ]
                },

                "D": {
                    "type": "object",
                    "additionalProperties": false,

                    "properties": {
                        "TypeDiscriminator": {
                            "type": "string",
                            "enum": [
                                "D"
                            ]
                        },

                        "SomeOtherValue": {
                            "type": "number"
                        }
                    },

                    "required": [
                        "TypeDiscriminator",
                        "SomeOtherValue"
                    ]
                }
            }
        }

    var startingObject = JSON.parse('{ '
        + '"A": "incididunt dolor", '
        + '"B": ['
        + '     {'
        + '         "TypeDiscriminator": "C"'
        + '     },'
        + '     {'
        + '         "TypeDiscriminator": "C"'
        + '     },'
        + '     {'
        + '         "TypeDiscriminator": "C"'
        + '     },'
        + '     {'
        + '         "TypeDiscriminator": "D"'
        + '     }'
        + ' ]'
        + '}')


    function arraySizeCallbackFunction(schemaPath) {
        // Trailing item should be a subscript, remove that too.
        var dataPath = schemaPath.filter(element => element !== "properties" && element !== "items");

        var data = ptr.get(startingObject, ptr.encodePointer(dataPath));
        // Trim "properties" and "items" out of the path,
        //
        // Use JSON pointer into startingObject

        return data.length;
    }

    function schemaChoiceCallbackFunction(schemaPath, options) {
        // Get the data at this path
        var dataPath = schemaPath.filter(element => element !== "properties" && element !== "items");
        //const OR single option enum on TypeDiscriminator
        var data = ptr.get(startingObject, ptr.encodePointer(dataPath));
        return options.find(schemaChoice => schemaChoice.properties.TypeDiscriminator.enum[0] === data.TypeDiscriminator)

    }

    // Source gets merged over target (the random Data)
    function oldArrayMerge(randomGenerated, sourceData, options) {
        // Set the array size to a max of the source data size.
        const destination = randomGenerated.slice(0, sourceData.length);
        // If the type matches, merge
        // else just merge the id field
        // Always clone

        sourceData.forEach(function (e, i) {
            if (typeof destination[i] === 'undefined') {
                destination[i] = traverse.clone(e)
            } else if (options.isMergeableObject(e)) {
                destination[i] = merge(randomGenerated[i], e, options)
            } else if (randomGenerated.indexOf(e) === -1) {
                destination.push(e)
            }
        })

        return destination
    }

    var randomData = await jsf.resolve(schema);

    // ok - now merge these - array merge should check array size and type discriminator
    var mergedData = merge(randomData, startingObject, { arrayMerge: oldArrayMerge });
    console.log(mergedData);

})();`

**Comment by pateketrueke** [comment]
Thank you, I'll check this out on my spare time, please be patient.

**Comment by alisters** [comment]
Absolutely no rush ! Below is the full example of the callback functions

// x is my state that i'm pulling in from the surrounding function
// I compare this with the data generated by json schema faker
// It's different for each time i call jsf - so i have to have to pull it 
// in somehow

function arraySizeCallbackFunction(schemaPath) {
    // Trailing item should be a subscript, remove that too.
    var startingObject = x;

   // Trim "properties" and "items" out of the path, to get the data path from the schema path
    var dataPath = schemaPath.filter(element => element !== "properties" && element !== "items");

    // This data is relative to the command we are running
// Use JSON pointer into startingObject
    var data = ptr.get(startingObject, ptr.encodePointer(dataPath));
    
    log.info(`Random data generation : Array Size Callback : SchemaPath {${schemaPath}}, $dataPath {${dataPath}}, Length ${data === undefined ? 0 : data.length}`)

    return data === undefined ? 0 : data.length;
}

function schemaChoiceCallbackFunction(schemaPath, schemaList) {
    var startingObject = x;
    // Get the data at this path
    var dataPath = schemaPath.filter(element => element !== "properties" && element !== "items");

    //const OR single option enum on TypeDiscriminator
    var data = ptr.get(startingObject, ptr.encodePointer(dataPath));
    // po is a propertyObject
    var selectedSchema = schemaList.find(schemaChoice => {
        var matchingDiscriminatorProperties =
            Object.entries(schemaChoice.properties).map(([name, value]) => ({ name, value }))
                .filter(property => property.value.hasOwnProperty("enum"))
                .filter(enumProperty => enumProperty.value.enum.length === 1)
                .filter(discriminator => data.hasOwnProperty(discriminator.name) && data[discriminator.name] === discriminator.value.enum[0]);

        return matchingDiscriminatorProperties.length === 1
    }
    );

    if (selectedSchema == undefined) {
        log.info(`Couldn't find a schema in the data at ${schemaPath}`);
    }
    else {
        log.info(`Random data generation : Schema Choice Callback : SchemaPath {${schemaPath}}, dataPath {${dataPath}}, Schema {${selectedSchema.title}}`)
    }

    return selectedSchema;

    //return schemaList.find(schemaChoice => schemaChoice.properties.TypeDiscriminator.enum[0] === data.TypeDiscriminator)

}

jsf.extend('faker', function () { return require('faker'); });
jsf.option({
    alwaysFakeOptionals: true,
    schemaChoiceCallback: schemaChoiceCallbackFunction,
    arraySizeCallback: arraySizeCallbackFunction
});

jsf.format('guid', function () {
    return chance.guid();
});

var randomData = jsf(currentSchema);

// https://github.com/KyleAMathews/deepmerge

log.info(`Merging data for ${node.path[0]} - generated ${randomData} `);
var mergedData = merge(randomData, x, { arrayMerge: oldArrayMerge });
node.update(mergedData);

            }

        }

    });

**Comment by pateketrueke** [comment]
I think you can implement this through custom keywords, open it if you want to discuss it here.

Thank you!

**Pull request closed without merging**
