### PR TITLE
#93 recursive schema's, suggested max traversal depth implementation

### PR DESCRIPTION
**Pull request by arjanvanderleden**
@ducin This is PR for the suggested implementation

### CODE REVIEW

**Comment by ducin** [comment]
revisiting #92

**Comment by swivelhinges** [comment]
Any update on when this merge conflict might be dealt with? This seems like a pretty big improvement

**Comment by felipecardona** [comment]
This library is awesome, and this feature is very important :(, anyway we can help?

**Comment by felipecardona** [comment]
Heavens!, thanks! :D

**Pull request merged**
