### PR TITLE
142 fix number generation

### PR DESCRIPTION
**Pull request by JonathanMontane**
This should improve the number generation space coverage.
It should solve #142.

### CODE REVIEW

**Comment by ducin** [comment]
Here it will be also problematic to merge. You are improving integer/number random generators. Why are you submitting changes on package.json automatic tasks (especially, that they make the tasks fail on my machine :) )? Moreover, the tests for `iojs` fail no matter how many times I re-try them.

We need to have this PR split into smaller pieces if we are to merge it.

**Comment by pateketrueke** [comment]
You're right, package scripts are fine atm, why change it?

**Comment by ducin** [comment]
One note. Changing the setup is perfectly fine as long as it's just a separate PR and doesn't get mixed with logic changes :)

**Comment by pateketrueke** [comment]
Hi again, I've tried to merge this changes locally but randomly fails.

@JonathanMontane did you ran the tests several times?

Hint: add, i.e. `"repeat": 10` to your json test and see what happens.

Anyway I'll push what I've merged into a separated branch just for run CI tests.

**Pull request merged**
