### PR TITLE
feat: register inner-references by id; closes #610

### LINKED ISSUE #610: json-schema-faker unable to resolve ref by id as  urn:jsonschema:xxxx:xxx
If you are reporting a bug, please include the following:

1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `Generate example` and then copy and paste the resulting URL from the browser address bar)
2. the result you got
3. the result you expected

**Input schema:** 
`{
  "type": "object",
  "id": "urn:jsonschema:spacerockk:habari:ws:som:LotAggregate",
  "properties": {
    "id": {
      "type": "string",
      "required": true
    },
    "CreateDate": {
      "type": "string"
    },
    "LastUpdate": {
      "type": "string"
    },
    "ItemCode": {
      "type": "object",
      "id": "urn:jsonschema:spacerockk:habari:ws:som:ItemCode",
      "properties": {
        "logger": {
          "type": "object",
          "id": "urn:jsonschema:com:spacerockk:log:TLScalaLogger",
          "properties": {
            "logger": {
              "type": "object",
              "id": "urn:jsonschema:org:slf4j:Logger",
              "properties": {
                "name": {
                  "type": "string"
                },
                "traceEnabled": {
                  "type": "boolean"
                },
                "debugEnabled": {
                  "type": "boolean"
                },
                "infoEnabled": {
                  "type": "boolean"
                },
                "warnEnabled": {
                  "type": "boolean"
                },
                "errorEnabled": {
                  "type": "boolean"
                }
              }
            },
            "debugEnabled": {
              "type": "boolean"
            }
          }
        },
        "ic": {
          "type": "string"
        },
        "ict": {
          "type": "string"
        }
      }
    },
    "ItemCodeProspects": {
      "type": "array",
      "items": {
        "$ref": "urn:jsonschema:spacerockk:habari:ws:som:ItemCode"
      }
    }
  }
}`

When I tried generating JSON Message using this schema, json-schema-faker is unable to generate. 

Tried parsing the ref's with  json-schema-ref-parser and got this following error,

`
stack: 'ResolverError: Error opening file "urn:jsonschema/:spacerokk:habari:ws:som:ItemCode" \n' +
    "ENOENT: no such file or directory, open 'urn:jsonschema/:spacerokk:habari:ws:som:ItemCode'\n" +
    '    at ReadFileContext.callback (/Users/pnalla/Desktop/fakeJson/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/file.js:52:20)\n' +
    '    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:264:13)',
  code: 'ERESOLVER',
  message: 'Error opening file "urn:jsonschema/:spacerokk:habari:ws:som:ItemCode" \n' +
    "ENOENT: no such file or directory, open 'urn:jsonschema/:spacerokk:habari:ws:som:ItemCode'",
  source: 'urn:jsonschema/:spacerokk:habari:ws:som:ItemCode',
  path: null,
  toJSON: [Function: toJSON],
  ioErrorCode: 'ENOENT',
  name: 'ResolverError',
  toString: [Function: toString]
}
`

Team, could you please look into this.

### PR DESCRIPTION
**Pull request by pateketrueke**

### CODE REVIEW

**Comment by parameshnalla** [comment]
Tested this feature with the following schema: 

**Input schema:** 

`{
  "type": "object",
  "id": "urn:jsonschema:spacerokk:habari:ws:som:LotAggregate",
  "properties": {
    "id": {
      "type": "string",
      "required": true
    },
    "CreateDate": {
      "type": "string"
    },
    "ItemCode": {
      "type": "object",
      "id": "urn:jsonschema:spacerokk:habari:ws:som:ItemCode",
      "properties": {
        "logger": {
          "type": "object",
          "id": "urn:jsonschema:com:spacerokk:log:TLScalaLogger",
          "properties": {
            "logger": {
              "type": "object",
              "id": "urn:jsonschema:org:slf4j:Logger",
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            }
          }
        },
        "ic": {
          "type": "string"
        },
        "ict": {
          "type": "string"
        }
      }
    },
    "ItemCodeProspects": {
      "type": "array",
      "items": {
        "$ref": "urn:jsonschema:spacerokk:habari:ws:som:ItemCode"
      }
    }
  }
}`

**Output generated:** 

`{
  "id": "occaecat consectetur adipisicing",
  "CreateDate": "et dolore officia",
  "ItemCode": {
    "logger": {
      "logger": {
        "name": "culpa"
      }
    },
    "ic": "do dolore consequat ut laboris",
    "ict": "commodo eu Duis consectetur pariatur"
  },
  "ItemCodeProspects": []
}`

ItemCodeProspects is not populating. @pateketrueke

**Comment by pateketrueke** [comment]
> ItemCodeProspects is not populating.

I that property is not in the `required` list, then it won't be generated all time, just few times, randomly.

Ensure you add that to the `required` list, or enforce it enabling the `alwaysFakeOptionals` option.

**Comment by parameshnalla** [comment]
@pateketrueke 

**The following script I'm using to generate message**

```
'use strict';
const jsf = require('./json-schema-faker'); // json-schema faker
const fs = require('fs'); // nodeJS file system library to read and write files

jsf.extend('faker', function(){
    var faker = require('faker');
    faker.locale = "en"; // or any other language
    faker.custom = {
      tags: function(length) {
        return faker.lorem.word() + "," + faker.lorem.word() + "," + faker.lorem.word();
      }
    };
    return faker;
  });

jsf.option('alwaysFakeOptionals', true);


var mySchema = {
  "type": "object",
  "id": "urn:jsonschema:spacerokk:habari:ws:som:LotAggregate",
  "properties": {
    "id": {
      "type": "string",
      "required": true
    },
    "CreateDate": {
      "type": "string"
    },
    "ItemCode": {
      "type": "object",
      "id": "urn:jsonschema:spacerokk:habari:ws:som:ItemCode",
      "properties": {
        "logger": {
          "type": "object",
          "id": "urn:jsonschema:com:spacerokk:log:TLScalaLogger",
          "properties": {
            "logger": {
              "type": "object",
              "id": "urn:jsonschema:org:slf4j:Logger",
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            }
          }
        },
        "ic": {
          "type": "string"
        },
        "ict": {
          "type": "string"
        }
      }
    },
    "ItemCodeProspects": {
      "type": "array",
      "items": {
        "$ref": "urn:jsonschema:spacerokk:habari:ws:som:ItemCode"
      }
    }
  }
}

   

jsf.resolve(mySchema).then(sample => {
  console.log(JSON.stringify(sample));
});
```

**Comment by pateketrueke** [comment]
You could add a `minItems` property in you `ItemCodeProspects` schema to enforce it.

**Comment by parameshnalla** [comment]
@pateketrueke Yes I tried that too, it gives a different error. 

``` {
  "type": "object",
  "id": "urn:jsonschema:spacerokk:habari:ws:som:LotAggregate",
  "properties": {
    "id": {
      "type": "string",
      "required": true
    },
    "CreateDate": {
      "type": "string"
    },
    "ItemCode": {
      "type": "object",
      "id": "urn:jsonschema:spacerokk:habari:ws:som:ItemCode",
      "properties": {
        "logger": {
          "type": "object",
          "id": "urn:jsonschema:com:spacerokk:log:TLScalaLogger",
          "properties": {
            "logger": {
              "type": "object",
              "id": "urn:jsonschema:org:slf4j:Logger",
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            }
          }
        },
        "ic": {
          "type": "string"
        },
        "ict": {
          "type": "string"
        }
      }
    },
    "ItemCodeProspects": {
      "type": "array",
      "items": {
        "name": "string",
        "$ref": "urn:jsonschema:spacerokk:habari:ws:som:ItemCode"
      },
      "minItems": "4"
    }
  }
}```

**Error:**

`(node:3211) UnhandledPromiseRejectionWarning: Error: Error while resolving schema (missing items for {
  "type": "array",
  "minItems": "4"
} in /properties/ItemCodeProspects)
    at /Users/pnalla/Desktop/fakeJson/json-schema-faker/dist/main.cjs.js:3106:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)`


When replaced the ref with inline schema with or without minItems works as expected. I believe refs are not resolving for ItemProspects, that's the reason it is failing when we are providing minItems.  In earlier case for ItemCodeProspects we don't have any properties it is giving []

**Comment by pateketrueke** [comment]
Good catch, I just pushed the final changes, it should work for you now.

**Comment by parameshnalla** [comment]
@pateketrueke  Thanks for the fix, it works now.
`{
  "id": "eu irure",
  "CreateDate": "et dolore Ut amet",
  "ItemCode": {
    "logger": {
      "logger": {
        "name": "do"
      }
    },
    "ic": "occaecat",
    "ict": "in quis tempor eiusmod proident"
  },
  "ItemCodeProspects": [
    {
      "logger": {
        "logger": {
          "name": "non dolore"
        }
      },
      "ic": "sed ad amet Excepteur",
      "ict": "culpa mollit veniam incididunt in"
    }
  ]
}`

**Pull request merged**
