### PR TITLE
Allow option to use default values

### PR DESCRIPTION
**Pull request by pksunkara**
@ducin @pateketrueke I would appreciate if this can be merged as soon as you can and released. Thanks.

### CODE REVIEW

**Comment by pateketrueke** [comment]
Please stick to our [contribution guidelines](https://github.com/json-schema-faker/json-schema-faker/blob/master/.github/CONTRIBUTING.md), add a few json tests and we can merge it asap. Thanks in advance!

**Comment by pksunkara** [comment]
@pateketrueke Hey, I am trying to find where to add the tests. Do you have any advice? Should it go into spec/schema/core/option ?

**Comment by pateketrueke** [comment]
That place is fine, because you are adding core functionality. ;)

**Comment by pksunkara** [comment]
@pateketrueke Added tests and updated.

**Comment by pateketrueke** [comment]
Awesome!

**Comment by pksunkara** [comment]
@pateketrueke Can you make a release and publish to npm please? Thanks.

**Comment by pateketrueke** [comment]
`v0.3.3` released, thanks for your feedback! 🍻

**Pull request merged**
